// Code generated by "stringer -type=OpType"; DO NOT EDIT.

package payload

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[read-0]
	_ = x[write-1]
	_ = x[payload-2]
}

const _OpType_name = "readwritepayload"

var _OpType_index = [...]uint8{0, 4, 9, 16}

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
